name: NPM Publish
on:
  workflow_run:
    workflows: ["Check"]
    branches: [master]
    types:
      - completed
jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' && !startsWith(github.event.head_commit.message, '[RELEASE]') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - run: cd ./app/src/api/ && npm ci
      - run: cd ./app/src/api/ && git config --global user.name 'Firebolt Caster'
      - run: cd ./app/src/api/ && git config --global user.email 'nilsbaumgartner@live.de'
      - run: cd ./app/src/api/ && git stash
      - run: cd ./app/src/api/ && npm run releaseCI
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
