name: NPM Publish
on:
  workflow_run:
    workflows: ["Check"]
    branches: [master]
    types:
      - completed
jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' && !startsWith(github.event.head_commit.message, '[RELEASE]') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - run: cd ./app/src/api/ && npm ci
      - run: cd ./app/src/api/ && git config --global user.name 'Firebolt Caster'
      - run: cd ./app/src/api/ && git config --global user.email 'nilsbaumgartner@live.de'
      - run: cd ./app/src/api/ && ls
      - run: cd ./app/src/api/ && git stash
      - run: cd ./app/src/api/ && ls && npm run releaseCI
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  gh-pages:
    if: ${{ github.event.workflow_run.conclusion == 'success' && !startsWith(github.event.head_commit.message, '[RELEASE]') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - run: cd ./app/ && npm ci
      - run: cd ./src/api/ && npm ci && cd ../../
      - run: git config --global user.name 'Firebolt Caster'
      - run: git config --global user.email 'nilsbaumgartner@live.de'
      #https://www.npmjs.com/package/gh-pages
      - run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          CI=false npm run deployghpages -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
